
#ifndef CPPPROJECTTEMPLATELIB_EXPORT_H
#define CPPPROJECTTEMPLATELIB_EXPORT_H

#ifdef CPPPROJECTTEMPLATELIB_STATIC_DEFINE
#  define CPPPROJECTTEMPLATELIB_EXPORT
#  define CPPPROJECTTEMPLATELIB_NO_EXPORT
#else
#  ifndef CPPPROJECTTEMPLATELIB_EXPORT
#    ifdef CppProjectTemplateLib_EXPORTS
        /* We are building this library */
#      define CPPPROJECTTEMPLATELIB_EXPORT 
#    else
        /* We are using this library */
#      define CPPPROJECTTEMPLATELIB_EXPORT 
#    endif
#  endif

#  ifndef CPPPROJECTTEMPLATELIB_NO_EXPORT
#    define CPPPROJECTTEMPLATELIB_NO_EXPORT 
#  endif
#endif

#ifndef CPPPROJECTTEMPLATELIB_DEPRECATED
#  define CPPPROJECTTEMPLATELIB_DEPRECATED __declspec(deprecated)
#endif

#ifndef CPPPROJECTTEMPLATELIB_DEPRECATED_EXPORT
#  define CPPPROJECTTEMPLATELIB_DEPRECATED_EXPORT CPPPROJECTTEMPLATELIB_EXPORT CPPPROJECTTEMPLATELIB_DEPRECATED
#endif

#ifndef CPPPROJECTTEMPLATELIB_DEPRECATED_NO_EXPORT
#  define CPPPROJECTTEMPLATELIB_DEPRECATED_NO_EXPORT CPPPROJECTTEMPLATELIB_NO_EXPORT CPPPROJECTTEMPLATELIB_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef CPPPROJECTTEMPLATELIB_NO_DEPRECATED
#    define CPPPROJECTTEMPLATELIB_NO_DEPRECATED
#  endif
#endif

#endif /* CPPPROJECTTEMPLATELIB_EXPORT_H */
